# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  metagraph-l0-1:
    container_name: metagraph-l0-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l0-genesis/Dockerfile
    image: metagraph-l0-initial-validator
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_GLOBAL_L0_PEER_HTTP_HOST=global-l0-1
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
      - SHOULD_RESET_GENESIS_FILE=${SHOULD_RESET_GENESIS_FILE}
      - FORCE_ROLLBACK=${FORCE_ROLLBACK}
    volumes:
      - ../shared/jars:/code/jars/
      - ../../../source/metagraph-l0/genesis:/code/genesis/
      - ../../../scripts/start_containers/start_genesis_metagraph.sh:/code/start_genesis_metagraph.sh
    ports:
      - '9400:9000'
      - '9401:9001'
    networks:
      custom-network:
        ipv4_address: 172.50.0.20
    command: >
      sh -c 'chmod a+rwx start_genesis_metagraph.sh && ./start_genesis_metagraph.sh'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://metagraph-l0-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true